global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using OneLetterShor;
global using OneLetterShor.SimpleSocd;
global using UnityEngine;
global using static OneLetterShor.SimpleSocd.Tests.Assertions;
global using Logger = OneLetterShor.SimpleSocd.Logging.Logger;